export class ObjetosPerfil {
    perfilHtml: string;
    perfilSinFactura: string;
    perfilInmediataMensual: string;
    perfilRetenidas: string;


    constructor() {
        this.perfilHtml = `{"columns":[{"visibleIndex":0,"dataField":"codigo",
        "dataType":"string","visible":true},{"visibleIndex":1,"dataField":"acuerdo",
        "dataType":"string","visible":true},{"visibleIndex":2,"dataField":"fecha_entrada",
        "dataType":"string","visible":true},{"visibleIndex":3,"dataField":"fecha_entrega",
        "dataType":"string","visible":true},{"visibleIndex":4,"dataField":"fecha_entrega_prevista",
        "dataType":"string","visible":true},{"visibleIndex":5,"dataField":"estado","dataType":"string",
        "visible":true},{"visibleIndex":6,"dataField":"serviciosfac1","dataType":"number","visible":true},
        {"visibleIndex":7,"dataField":"total","dataType":"number","visible":true},{"visibleIndex":8,
        "dataField":"pedidoenfactura","dataType":"boolean","visible":true},{"visibleIndex":9,"dataField":"req_no_mezclar",
        "dataType":"boolean","visible":true},{"visibleIndex":10,"dataField":"agrupar_facturas_analiticas",
        "dataType":"boolean","visible":true},{"visibleIndex":11,"dataField":"desglosar_direccion_envio",
        "dataType":"boolean","visible":true},{"visibleIndex":12,"dataField":"direccion_envio","dataType":"number",
        "visible":true},{"visibleIndex":13,"dataField":"referencia_cliente","dataType":"string","width":100,"visible":true},
        {"visibleIndex":14,"dataField":"cliente_oid","dataType":"number","width":200,"visible":true},
        {"visibleIndex":15,"dataField":"factura_a","dataType":"number","width":200,"visible":true},
        {"visibleIndex":16,"dataField":"codigo_proyecto","dataType":"string","visible":true},
        {"visibleIndex":17,"dataField":"codigo_tarea","dataType":"string","visible":true},
        {"visibleIndex":18,"dataField":"codigo_subtarea","dataType":"string","visible":true},
        {"visibleIndex":19,"dataField":"emails_envio","dataType":"string","width":150,"visible":true},
        {"visibleIndex":20,"dataField":"tipologia","dataType":"number","visible":true},{"visibleIndex":21,
        "dataField":"tipo_facturacion","dataType":"number","visible":true},{"visibleIndex":22,
        "dataField":"tipo_facturacion_cliente","dataType":"number","visible":true},{"visibleIndex":23,
        "dataField":"envio_automatico","dataType":"number","visible":true},{"visibleIndex":24,"dataField":"retenida",
        "dataType":"boolean","visible":true},{"visibleIndex":25,"dataField":"observaciones","dataType":"string",
        "visible":true},{"visibleIndex":26,"dataField":"observaciones_so","dataType":"string","visible":true},
        {"visibleIndex":27,"dataField":"observaciones_fac","visible":true},{"visibleIndex":28,"dataField":"codigo_prefactura",
        "visible":false},{"visibleIndex":29,"dataField":"codigo_factura","visible":false},{"visibleIndex":30,"dataField":"codigo_abono",
        "visible":false},{"visibleIndex":31,"dataField":"importe","dataType":"number","visible":true}],"allowedPageSizes":[25,50,100],
        "filterPanel":{"filterEnabled":true},"filterValue":null,"searchText":"","pageIndex":0,"pageSize":50}`;
        this.perfilSinFactura = `{"columns":[{"visibleIndex":0,"dataField":"codigo","dataType":"string","visible":true,"fixed":true,"fixedPosition":"left"},{"visibleIndex":1,"dataField":"acuerdo","dataType":"string","visible":false},{"visibleIndex":3,"dataField":"fecha_entrada","dataType":"string","visible":true},{"visibleIndex":4,"dataField":"fecha_entrega","dataType":"string","visible":true},{"visibleIndex":5,"dataField":"fecha_entrega_prevista","dataType":"string","visible":true},{"visibleIndex":14,"dataField":"estado","dataType":"string","visible":false},{"visibleIndex":15,"dataField":"serviciosfac1","dataType":"number","visible":false},{"visibleIndex":16,"dataField":"total","dataType":"number","visible":false},{"visibleIndex":17,"dataField":"pedidoenfactura","dataType":"boolean","visible":false},{"visibleIndex":18,"dataField":"req_no_mezclar","dataType":"boolean","visible":false},{"visibleIndex":19,"dataField":"agrupar_facturas_analiticas","dataType":"boolean","visible":false},{"visibleIndex":20,"dataField":"desglosar_direccion_envio","dataType":"boolean","visible":false},{"visibleIndex":21,"dataField":"direccion_envio","dataType":"number","visible":false},{"visibleIndex":9,"dataField":"referencia_cliente","dataType":"string","width":100,"visible":true},{"visibleIndex":22,"dataField":"cliente_oid","dataType":"number","width":200,"visible":false},{"visibleIndex":2,"dataField":"factura_a","dataType":"number","width":200,"visible":true},{"visibleIndex":6,"dataField":"codigo_proyecto","dataType":"string","visible":true},{"visibleIndex":7,"dataField":"codigo_tarea","dataType":"string","visible":true},{"visibleIndex":8,"dataField":"codigo_subtarea","dataType":"string","visible":true},{"visibleIndex":23,"dataField":"emails_envio","dataType":"string","width":150,"visible":false},{"visibleIndex":24,"dataField":"tipologia","dataType":"number","visible":false},{"visibleIndex":10,"dataField":"tipo_facturacion","dataType":"number","visible":true},{"visibleIndex":25,"dataField":"tipo_facturacion_cliente","dataType":"number","visible":false},{"visibleIndex":26,"dataField":"envio_automatico","dataType":"number","visible":false},{"visibleIndex":12,"dataField":"retenida","dataType":"boolean","visible":true},{"visibleIndex":27,"dataField":"observaciones","dataType":"string","visible":false},{"visibleIndex":28,"dataField":"observaciones_so","dataType":"string","visible":false},{"visibleIndex":11,"dataField":"observaciones_fac","dataType":"string","visible":true},{"visibleIndex":29,"dataField":"codigo_prefactura","visible":false},{"visibleIndex":30,"dataField":"codigo_factura","visible":false},{"visibleIndex":31,"dataField":"codigo_abono","visible":false},{"visibleIndex":13,"dataField":"importe","dataType":"number","visible":true}],"allowedPageSizes":[25,50,100],"filterPanel":{"filterEnabled":true},"filterValue":null,"searchText":"","pageIndex":0,"pageSize":50,"selectedRowKeys":[]}`;
        this.perfilInmediataMensual = `{"columns":[{"visibleIndex":0,"dataField":"codigo","dataType":"string","visible":true,"fixed":true,"fixedPosition":"left"},{"visibleIndex":4,"dataField":"acuerdo","dataType":"string","visible":false},{"visibleIndex":5,"dataField":"fecha_entrada","dataType":"string","visible":true},{"visibleIndex":6,"dataField":"fecha_entrega","dataType":"string","visible":true},{"visibleIndex":7,"dataField":"fecha_entrega_prevista","dataType":"string","visible":false},{"visibleIndex":9,"dataField":"estado","dataType":"string","visible":false},{"visibleIndex":12,"dataField":"serviciosfac1","dataType":"number","visible":false},{"visibleIndex":11,"dataField":"total","dataType":"number","visible":true},{"visibleIndex":13,"dataField":"pedidoenfactura","dataType":"boolean","visible":false},{"visibleIndex":14,"dataField":"req_no_mezclar","dataType":"boolean","visible":true},{"visibleIndex":16,"dataField":"agrupar_facturas_analiticas","dataType":"boolean","visible":true},{"visibleIndex":15,"dataField":"desglosar_direccion_envio","dataType":"boolean","visible":true},{"visibleIndex":2,"dataField":"direccion_envio","dataType":"number","visible":true},{"visibleIndex":8,"dataField":"referencia_cliente","dataType":"string","width":100,"visible":true},{"visibleIndex":1,"dataField":"cliente_oid","dataType":"number","width":200,"visible":true},{"visibleIndex":3,"dataField":"factura_a","dataType":"number","width":200,"visible":true},{"visibleIndex":20,"dataField":"codigo_proyecto","dataType":"string","visible":false},{"visibleIndex":21,"dataField":"codigo_tarea","dataType":"string","visible":false},{"visibleIndex":22,"dataField":"codigo_subtarea","dataType":"string","visible":false},{"visibleIndex":23,"dataField":"emails_envio","dataType":"string","width":150,"visible":false},{"visibleIndex":10,"dataField":"tipologia","dataType":"number","visible":true},{"visibleIndex":17,"dataField":"tipo_facturacion","dataType":"number","visible":true},{"visibleIndex":18,"dataField":"tipo_facturacion_cliente","dataType":"number","visible":true},{"visibleIndex":24,"dataField":"envio_automatico","dataType":"number","visible":false},{"visibleIndex":25,"dataField":"retenida","dataType":"boolean","visible":true},{"visibleIndex":26,"dataField":"observaciones","dataType":"string","visible":false},{"visibleIndex":27,"dataField":"observaciones_so","dataType":"string","visible":false},{"visibleIndex":19,"dataField":"observaciones_fac","visible":true},{"visibleIndex":28,"dataField":"codigo_prefactura","visible":false},{"visibleIndex":29,"dataField":"codigo_factura","visible":false},{"visibleIndex":30,"dataField":"codigo_abono","visible":false},{"visibleIndex":31,"dataField":"importe","dataType":"number","visible":true}],"allowedPageSizes":[25,50,100],"filterPanel":{"filterEnabled":true},"filterValue":null,"searchText":"","pageIndex":0,"pageSize":50}`;
        this.perfilRetenidas = `{"columns":[{"visibleIndex":0,"dataField":"codigo","dataType":"string","visible":true,"fixed":true,"fixedPosition":"left"},{"visibleIndex":4,"dataField":"acuerdo","dataType":"string","visible":false},{"visibleIndex":5,"dataField":"fecha_entrada","dataType":"string","visible":true},{"visibleIndex":6,"dataField":"fecha_entrega","dataType":"string","visible":true},{"visibleIndex":7,"dataField":"fecha_entrega_prevista","dataType":"string","visible":false},{"visibleIndex":9,"dataField":"estado","dataType":"string","visible":false},{"visibleIndex":12,"dataField":"serviciosfac1","dataType":"number","visible":false},{"visibleIndex":11,"dataField":"total","dataType":"number","visible":true},{"visibleIndex":13,"dataField":"pedidoenfactura","dataType":"boolean","visible":false},{"visibleIndex":14,"dataField":"req_no_mezclar","dataType":"boolean","visible":false,"sortOrder":"desc","sortIndex":0},{"visibleIndex":16,"dataField":"agrupar_facturas_analiticas","dataType":"boolean","visible":false},{"visibleIndex":15,"dataField":"desglosar_direccion_envio","dataType":"boolean","visible":false},{"visibleIndex":2,"dataField":"direccion_envio","dataType":"number","visible":true},{"visibleIndex":8,"dataField":"referencia_cliente","dataType":"string","width":100,"visible":true},{"visibleIndex":1,"dataField":"cliente_oid","dataType":"number","width":200,"visible":true},{"visibleIndex":3,"dataField":"factura_a","dataType":"number","width":200,"visible":true},{"visibleIndex":19,"dataField":"codigo_proyecto","dataType":"string","visible":true},{"visibleIndex":20,"dataField":"codigo_tarea","dataType":"string","visible":true},{"visibleIndex":21,"dataField":"codigo_subtarea","dataType":"string","visible":true},{"visibleIndex":23,"dataField":"emails_envio","dataType":"string","width":150,"visible":false},{"visibleIndex":10,"dataField":"tipologia","dataType":"number","visible":true},{"visibleIndex":17,"dataField":"tipo_facturacion","dataType":"number","visible":true},{"visibleIndex":18,"dataField":"tipo_facturacion_cliente","dataType":"number","visible":true},{"visibleIndex":24,"dataField":"envio_automatico","dataType":"number","visible":false},{"visibleIndex":25,"dataField":"retenida","dataType":"boolean","visible":true},{"visibleIndex":26,"dataField":"observaciones","dataType":"string","visible":false},{"visibleIndex":27,"dataField":"observaciones_so","dataType":"string","visible":false},{"visibleIndex":22,"dataField":"observaciones_fac","visible":true},{"visibleIndex":28,"dataField":"codigo_prefactura","visible":false},{"visibleIndex":29,"dataField":"codigo_factura","visible":false},{"visibleIndex":30,"dataField":"codigo_abono","visible":false},{"visibleIndex":31,"dataField":"importe","dataType":"number","visible":true}],"allowedPageSizes":[25,50,100],"filterPanel":{"filterEnabled":true},"filterValue":null,"searchText":"","pageIndex":0,"pageSize":50}`;

    }
}